spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qdbest/config-repo.git
          basedir: /home/qdbest/IdeaProjects/study/sell/config//config-repo/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/