spring:
  application:
    name: auth-server
server:
  port: 7777
  context-path: /uaa
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true